apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  annotations:
    workflows.argoproj.io/default-artifact-repository: s3-artifact-repository
data:
  s3-artifact-repository: "s3: \n  bucket: argo-artifact-repository\n  endpoint: s3-a.zhw.cloud.switch.ch\n  insecure: false\n  accessKeySecret:\n    name: artifacts-s3\n    key: accesskey\n  secretKeySecret:\n    name: artifacts-s3\n    key: secretkey\n"
