apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces.yaml
  - "https://github.com/argoproj/argo-workflows/manifests/cluster-install?ref=v3.6.2"
  - ./service-account-token.yaml
  - ./artifact-repository-configmap.yaml
  - ./s3-qlever-workflow.yaml
patches:
- path: patch-list-namespaces.yaml
  target:
    kind: ClusterRole
    name: argo-cluster-role
- path: patch-add-role-ns.yaml
  target:
    kind: ClusterRoleBinding
    name: argo-server-binding
- path: patch-add-role-ns.yaml
  target:
    kind: ClusterRoleBinding
    name: argo-binding
namespace: argo
