creation_rules:
  - path_regex: secrets/.*
    encrypted_regex: "^.*(user|password|token|key)"
    age: >-
      age1km50yt89npfghhnk4j6xrf0cxhvefd2vr9aj9z70ycfsgu2q73jqg7f7f4,
      age107e7w608czn3n7hquwe49g5589yzwrtd7dcll9g9d9uvnhqnldgsvr8fsh
