apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces.yaml
  - ./qlever-pvc.yaml
  - ./helm/out/qlever/templates/deployment-server.yaml
  - ./helm/out/qlever/templates/deployment-ui.yaml
  - ./helm/out/qlever/templates/service-server.yaml
  - ./helm/out/qlever/templates/service-ui.yaml
namespace: qlever
