---
# Source: solr-external/charts/solr/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solr-catplus
  namespace: "default"
  labels:
    app.kubernetes.io/instance: solr-catplus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: solr
    app.kubernetes.io/version: 9.8.0
    helm.sh/chart: solr-9.5.3
    app.kubernetes.io/component: solr
automountServiceAccountToken: false
