apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: aws-wf
spec:
  schedule: "* * * * *"
  workflowSpec:
    entrypoint: s3-fetch-example
    templates:
      - name: s3-fetch-example
        container:
          image: amazon/aws-cli  # AWS CLI image
          command: [sh, -c]
          args:
            - aws --debug s3 ls --region us-east-1 --no-sign-request s3://giab
