---
# Source: solr-external/charts/solr/charts/zookeeper/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: solr-catplus-zookeeper
  namespace: default
  labels:
    app.kubernetes.io/instance: solr-catplus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 3.9.3
    helm.sh/chart: zookeeper-13.7.2
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: solr-catplus
      app.kubernetes.io/name: zookeeper
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    # Allow inbound connections to ZooKeeper
    - ports:
        - port: 2181
    # Allow internal communications between nodes
    - ports:
        - port: 2888
        - port: 3888
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: solr-catplus
              app.kubernetes.io/name: zookeeper
