---
# Source: solr-external/charts/solr/charts/zookeeper/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: solr-catplus-zookeeper
  namespace: default
  labels:
    app.kubernetes.io/instance: solr-catplus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 3.9.3
    helm.sh/chart: zookeeper-13.7.2
    app.kubernetes.io/component: zookeeper
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-client
      port: 2181
      targetPort: client
      nodePort: null
    - name: tcp-follower
      port: 2888
      targetPort: follower
    - name: tcp-election
      port: 3888
      targetPort: election
  selector:
    app.kubernetes.io/instance: solr-catplus
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: zookeeper
