apiVersion: v1
data:
  accesskey: ENC[AES256_GCM,data:N+p30IE+MYKKFfr877VSUP/lt6Y5RRkTosiR4EQP3wxq7w7IaZqXbKl5LCA=,iv:QYcfBSdsMUFMrInuF3hdmfYfSnQPhB0yaRzmT3Kr64c=,tag:s9FG0MOJw/aBTZAR+Mb+XA==,type:str]
  secretkey: ENC[AES256_GCM,data:GJ7akIIivo5oqbOxfIBdwI4FI7XwKkv1IP2mTIMUaOPBBrxY3vz8VOkHoTw=,iv:Lpmx1OMRmlKOtSlcQGiHSi3+AXT1v9ZwW7ZMEjf9ydY=,tag:MnJ2LtbDZpLGCiViRryrnw==,type:str]
kind: Secret
metadata:
  name: artifacts-s3
  namespace: argo
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1km50yt89npfghhnk4j6xrf0cxhvefd2vr9aj9z70ycfsgu2q73jqg7f7f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNkNzVkIzQ0dueEdkZnRq
        UUhNSHY1Mm8ySHgxTGZOMzN1YW9Tdmd4VUFJCnBoaitmMWloWUI4SGIxcHFHVjVn
        eVhiSWY4TlEvS1BWY29QQ1RnRUJVeEEKLS0tIExDWksvQnh2KzZDWGo4ODVUM1ZB
        cTBuYWNmZlFydVdVNWpSUldTOG5YWncKKqz7yY2WyJhd1XTD0+CZAmohh+V7Gtwu
        DZevan/a1mU9th90KKrPZ5piKHqTi7uAx9x9wajlgZr99L8hApqnzQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age107e7w608czn3n7hquwe49g5589yzwrtd7dcll9g9d9uvnhqnldgsvr8fsh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvckJuK3p0KzZueGMrZzlN
        TExlbnJ4M3JrUThVNDVTRjZHR01NZ0VHUTNzCmRDbk8vWk1VYkhSaEhDMzJPSXM0
        dzFyZHplemU4cURuMEtoYy84TVh5d0UKLS0tIGFqUjhtTENWVG41UVBzb3JralZq
        STdKUXczclRWM2pPVTRnQkkvL1k5elUKsKAFnnOs7s2w8rtuESItDKjwVgau/Wuv
        t+vHwTmWmvJdzmOmIw/JLpwPtnmRmcm4RJyaNXho/v3Mlt4pOkpsMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-20T14:54:12Z"
  mac: ENC[AES256_GCM,data:DCoNtJdTEiN4sg2Zr1O2U4L+xLiTpZ79lwcGmjiEwqCmH50c4rhItpuUSC/EfmmdCp4sxgIojCNc8K1kCai5Ok62xznMcUomjURZ+aMIIrpJXySU01aP+etOABVMj3ij30jfzVv5lFoSZTU8KUFy27TdoKEaQ7UeN0On/9kNMNo=,iv:NrPNX4Um9qO5D7jX7751Z2z5mSaCH9eCx6pYHCgIvDY=,tag:su9qMm27KxkWobrMYzmgxg==,type:str]
  pgp: []
  encrypted_regex: ^.*(user|password|token|key)
  version: 3.9.3
